export const DISEASES = [
  {
    id: 'citrus_canker',
    name: 'Citrus Canker',
    sci: 'Xanthomonas axonopodis pv. citri',
    icon: '🍂',
    color: '#DC2626',
    bg: '#FEE2E2',
    type: 'Bacterial',
    severity: 'high',
    desc: 'Bacterial disease causing raised, corky, water-soaked lesions on leaves, stems, and fruit. Spreads rapidly in warm, wet, windy conditions.',
    symptoms: ['Raised, corky lesions with yellow halos on leaves', 'Lesions on fruit reduce market value', 'Premature fruit drop', 'Twig dieback in severe cases'],
    treatments: {
      chemical: [
        'Copper Oxychloride 50% WP @ 3g/L every 15 days',
        'Bordeaux Mixture (1%) — 3 sprays at 15-day intervals',
        'Streptocycline 200ppm + Copper Oxychloride tank mix',
      ],
      organic: [
        'Neem oil 2% as preventive spray',
        'Remove and burn infected plant parts immediately',
        'Disinfect pruning tools with 70% isopropyl alcohol',
      ],
      preventive: [
        'Plant windbreaks to minimize wind-driven spread',
        'Use certified disease-free nursery stock only',
        'Avoid overhead irrigation — use drip instead',
      ],
    },
    marathi: 'लिंबू कँकर हा जीवाणूजन्य रोग आहे. संक्रमित भाग काढा आणि तांबेयुक्त बुरशीनाशक फवारणी दर पंधरा दिवसांनी करा.',
    hindi: 'सिट्रस कैंकर एक जीवाणु रोग है। संक्रमित भाग हटाएं और हर पंद्रह दिन में तांबे आधारित कवकनाशक का छिड़काव करें।',
  },
  {
    id: 'hlb',
    name: 'Huanglongbing (HLB)',
    sci: 'Candidatus Liberibacter asiaticus',
    icon: '🌿',
    color: '#D97706',
    bg: '#FEF3C7',
    type: 'Bacterial',
    severity: 'critical',
    desc: 'Called Citrus Greening — the most destructive citrus disease worldwide. Spread by Asian Citrus Psyllid. No cure exists; management only.',
    symptoms: ['Asymmetric blotchy mottling of leaves', 'Fruits small, lopsided, bitter', 'Premature fruit drop', 'Zinc deficiency-like symptoms'],
    treatments: {
      chemical: [
        'Imidacloprid 17.8% SL @ 0.5ml/L for psyllid vector control',
        'Thiamethoxam 25% WG @ 0.3g/L to control Asian Citrus Psyllid',
        'Trunk injection with oxytetracycline (experimental)',
      ],
      organic: [
        'Remove and immediately destroy infected trees',
        'Release Tamarixia radiata (natural psyllid predator)',
        'Reflective silver mulch to deter psyllid landing',
      ],
      preventive: [
        'Use only HLB-free certified nursery plants',
        'Regular scouting for Asian Citrus Psyllid',
        'Establish insect-proof screen nurseries',
      ],
    },
    marathi: 'हुआंगलोंगबिंग हा लिंबूवर्गीय झाडांचा सर्वात घातक रोग आहे. संक्रमित झाडे त्वरित काढून जाळा.',
    hindi: 'हुआंगलोंगबिंग खट्टे फलों की सबसे विनाशकारी बीमारी है। संक्रमित पेड़ तुरंत हटाकर जलाएं।',
  },
  {
    id: 'black_spot',
    name: 'Citrus Black Spot',
    sci: 'Phyllosticta citricarpa',
    icon: '⚫',
    color: '#1F2937',
    bg: '#F3F4F6',
    type: 'Fungal',
    severity: 'medium',
    desc: 'Fungal disease affecting fruit quality with distinctive black spots on rind. Reduces export quality and market value significantly.',
    symptoms: ['Circular black spots with grey centres on fruit', 'Freckle spots on young fruit', 'Virulent spots on ripe fruit', 'Premature fruit colouring'],
    treatments: {
      chemical: [
        'Mancozeb 75% WP @ 2g/L at fortnightly intervals',
        'Carbendazim 50% WP @ 1g/L during fruit development',
        'Propiconazole 25% EC @ 1ml/L for severe infections',
      ],
      organic: [
        'Kaolin clay particle films as physical barrier',
        'Sulfur-based fungicides (wettable sulfur 80%)',
        'Improve canopy aeration through regular pruning',
      ],
      preventive: [
        'Collect and destroy fallen infected fruit',
        'Maintain proper spacing for air circulation',
        'Avoid excessive nitrogen fertilisation',
      ],
    },
    marathi: 'सिट्रस ब्लॅक स्पॉट हा बुरशीजन्य रोग आहे. मॅन्कोझेब दोन ग्रॅम प्रति लिटर पाण्यात मिसळून फवारणी करा.',
    hindi: 'सिट्रस ब्लैक स्पॉट एक कवक रोग है। मैंकोज़ेब दो ग्राम प्रति लीटर पानी में मिलाकर छिड़काव करें।',
  },
  {
    id: 'root_rot',
    name: 'Phytophthora Root Rot',
    sci: 'Phytophthora parasitica / P. citrophthora',
    icon: '🌱',
    color: '#7C3AED',
    bg: '#EDE9FE',
    type: 'Oomycete',
    severity: 'high',
    desc: 'Water mould causing root and crown rot. Thrives in waterlogged soils, leading to progressive tree decline and death.',
    symptoms: ['Yellow leaves and wilting canopy', 'Gummosis (gum oozing) at trunk base', 'Dark discolouration of roots', 'Stunted growth and tree decline'],
    treatments: {
      chemical: [
        'Metalaxyl-M 4% + Mancozeb 64% WP @ 2.5g/L soil drench',
        'Fosetyl-Al 80% WP foliar spray @ 3g/L',
        'Phosphonate systemic fungicide trunk injection',
      ],
      organic: [
        'Trichoderma harzianum biocontrol @ 10g/plant soil application',
        'Improve soil drainage — create raised beds or mounds',
        'Mulch surface with organic matter away from trunk',
      ],
      preventive: [
        'Plant on well-drained soils or raised beds',
        'Avoid overwatering and waterlogging',
        'Graft onto Phytophthora-resistant rootstocks (Trifoliate)',
      ],
    },
    marathi: 'फायटोफ्थोरा मूळ कुजणे हा जास्त ओलाव्यामुळे होणारा रोग आहे. पाण्याचा निचरा सुधारा आणि ट्रायकोडर्मा बुरशीनाशक वापरा.',
    hindi: 'फाइटोफ्थोरा जड़ सड़न अधिक पानी के कारण होती है। जल निकासी सुधारें और ट्राइकोडर्मा जैव कवकनाशक का उपयोग करें।',
  },
  {
    id: 'melanose',
    name: 'Melanose',
    sci: 'Diaporthe citri',
    icon: '🟤',
    color: '#92400E',
    bg: '#FEF3C7',
    type: 'Fungal',
    severity: 'low',
    desc: 'Fungal disease causing rough, brownish mudcake-like specks on fruit skin. Primarily cosmetic but reduces premium fruit market value.',
    symptoms: ['Small, raised, dark-brown specks on fruit', '"Mudcake" pattern on fruit surface', 'Teardrop-shaped lesions on young leaves', 'Mainly affects fruit appearance'],
    treatments: {
      chemical: [
        'Copper Oxychloride 50% WP @ 3g/L — spray after new flush',
        'Mancozeb 75% WP @ 2g/L at 15-day intervals',
        'Bordeaux Mixture 0.6% spray after rain',
      ],
      organic: [
        'Remove dead wood which harbours the fungus',
        'Copper-based organic certified sprays',
        'Prune to improve light penetration',
      ],
      preventive: [
        'Annual pruning of dead and diseased branches',
        'Apply copper sprays before monsoon season',
        'Ensure good canopy light penetration',
      ],
    },
    marathi: 'मेलॅनोज हा बुरशीजन्य रोग आहे. मृत फांद्या काढा आणि तांबेयुक्त बुरशीनाशक फवारणी करा.',
    hindi: 'मेलेनोज एक कवक रोग है। मृत शाखाएं काटें और तांबे का कवकनाशक छिड़काव करें।',
  },
  {
    id: 'sooty_mould',
    name: 'Sooty Mould',
    sci: 'Capnodium citri',
    icon: '🌫️',
    color: '#4B5563',
    bg: '#F3F4F6',
    type: 'Fungal (Secondary)',
    severity: 'low',
    desc: 'Black fungal coating grows on honeydew secreted by sap-sucking insects. Blocks photosynthesis and weakens the plant.',
    symptoms: ['Black, powdery coating on leaves and twigs', 'Coating wipes off to reveal healthy tissue', 'Reduced photosynthesis and plant vigour', 'Associated with aphids, mealybugs, scale insects'],
    treatments: {
      chemical: [
        'Imidacloprid @ 0.5ml/L to control vector insects',
        'Dimethoate 30% EC @ 1.5ml/L for scale insects',
        'Starch spray (10%) to lift and remove sooty coating',
      ],
      organic: [
        'Neem oil 2% to control mealybugs and aphids',
        'Introduce predatory insects (ladybirds, lacewings)',
        'Strong water jet to wash off loose mould',
      ],
      preventive: [
        'Control ant populations that protect honeydew insects',
        'Regular inspection for sap-sucking insects',
        'Maintain plant nutrition to improve natural resistance',
      ],
    },
    marathi: 'सूटी मोल्ड हा रोग किडींच्या मलमूत्रावर बुरशी वाढल्याने होतो. कीटकनाशक फवारणी करा.',
    hindi: 'सूटी मोल्ड कीड़ों के मलमूत्र पर कवक उगने से होता है। कीटनाशक का छिड़काव करें।',
  },
  {
    id: 'tristeza',
    name: 'Citrus Tristeza Virus',
    sci: 'Citrus tristeza closterovirus (CTV)',
    icon: '🍃',
    color: '#15803D',
    bg: '#DCFCE7',
    type: 'Viral',
    severity: 'critical',
    desc: 'Highly destructive virus spread by brown citrus aphid. Causes stem pitting, seedling yellows, and quick decline on susceptible rootstocks.',
    symptoms: ['Stem pitting on trunk and branches', 'Small pale leaves with vein clearing', 'Quick decline with fruit still on tree', 'Honeybee-cell pattern in wood cross-section'],
    treatments: {
      chemical: [
        'Imidacloprid / Thiamethoxam to control aphid vectors',
        'Mineral oil sprays to reduce aphid populations',
        'No direct chemical cure for the virus',
      ],
      organic: [
        'Remove and burn heavily infected trees',
        'Release Lysiphlebus testaceipes parasitic wasps',
        'Use aphid-resistant rootstocks (Swingle citrumelo)',
      ],
      preventive: [
        'Plant certified Tristeza-tested budwood only',
        'Cross-protect with mild CTV strains',
        'Regular ELISA testing of planting material',
      ],
    },
    marathi: 'सिट्रस ट्रिस्टेझा हा विषाणूजन्य रोग आहे. माशांचे नियंत्रण करा आणि संक्रमित झाडे जाळा.',
    hindi: 'सिट्रस ट्रिस्टेज़ा एक वायरस रोग है। एफिड्स को नियंत्रित करें और संक्रमित पेड़ जलाएं।',
  },
  {
    id: 'scab',
    name: 'Citrus Scab',
    sci: 'Elsinoe fawcettii / Elsinoe australis',
    icon: '🔴',
    color: '#B45309',
    bg: '#FEF3C7',
    type: 'Fungal',
    severity: 'medium',
    desc: 'Fungal disease causing rough, scab-like outgrowths on young leaves, twigs, and fruit. Worst in humid, wet weather during flush growth.',
    symptoms: ['Pink-grey wart-like projections on leaves', 'Distortion and twisting of young leaves', 'Rough, irregular lesions on fruit skin', 'Premature fruit drop'],
    treatments: {
      chemical: [
        'Copper Oxychloride 50% WP @ 3g/L at bud-break',
        'Carbendazim 50% WP @ 1g/L during flush growth',
        'Mancozeb + Metalaxyl @ 2g/L for severe cases',
      ],
      organic: [
        'Prune and destroy infected tissue before wet season',
        'Wettable sulfur 80% WP @ 3g/L spray',
        'Improve air circulation through canopy management',
      ],
      preventive: [
        'Spray copper fungicide at every new flush emergence',
        'Avoid irrigating during susceptible flush periods',
        'Remove inoculum by pruning affected wood',
      ],
    },
    marathi: 'सिट्रस स्कॅब हा बुरशीजन्य रोग आहे. नवीन पालवीवर तांबेयुक्त बुरशीनाशक फवारणी करा.',
    hindi: 'सिट्रस स्कैब एक कवक रोग है। नई पत्तियों पर तांबे का कवकनाशक छिड़काव करें।',
  },
  {
    id: 'healthy',
    name: 'Healthy Plant',
    sci: 'No pathogen detected',
    icon: '✅',
    color: '#16A34A',
    bg: '#DCFCE7',
    type: 'Healthy',
    severity: 'none',
    desc: 'The plant appears healthy with no visible disease symptoms. Continue regular preventive care and monitoring schedule.',
    symptoms: ['Deep green uniform foliage', 'No lesions, spots or discolouration', 'Normal fruit development', 'Vigorous new flush growth'],
    treatments: {
      chemical: [
        'Routine preventive copper spray (0.5%) once a month',
        'Balanced NPK fertilisation (19:19:19 @ 2g/L foliar)',
        'Micronutrient spray (Zinc + Boron) at fruit set',
      ],
      organic: [
        'Vermicompost application @ 2kg per tree quarterly',
        'Neem cake soil application @ 200g per tree',
        'Jeevamrut foliar spray for micronutrients',
      ],
      preventive: [
        'Inspect plants every 2 weeks for early symptoms',
        'Maintain proper irrigation — avoid water stress',
        'Keep records of growth and spray schedule',
      ],
    },
    marathi: 'झाड पूर्णपणे निरोगी आहे! नियमित काळजी आणि महिन्यातून एकदा तपासणी करत राहा.',
    hindi: 'पेड़ पूरी तरह स्वस्थ है! नियमित देखभाल और महीने में एक बार जांच जारी रखें।',
  },
]

export const SEVERITY_LEVELS = {
  none:     { label: 'None',     color: '#16A34A', bg: '#DCFCE7', order: 0 },
  low:      { label: 'Low',      color: '#D97706', bg: '#FEF3C7', order: 1 },
  medium:   { label: 'Medium',   color: '#EA580C', bg: '#FFEDD5', order: 2 },
  high:     { label: 'High',     color: '#DC2626', bg: '#FEE2E2', order: 3 },
  critical: { label: 'Critical', color: '#7F1D1D', bg: '#FECACA', order: 4 },
}

export const GEO_DISTRICTS = [
  { name: 'Nagpur',     lat: 21.14, lng: 79.08, x: 0.52, y: 0.32, reports: 24, severity: 'high'   },
  { name: 'Amravati',   lat: 20.93, lng: 77.75, x: 0.35, y: 0.45, reports: 18, severity: 'medium' },
  { name: 'Wardha',     lat: 20.74, lng: 78.60, x: 0.47, y: 0.52, reports: 11, severity: 'medium' },
  { name: 'Yavatmal',   lat: 20.40, lng: 78.12, x: 0.40, y: 0.65, reports: 19, severity: 'high'   },
  { name: 'Chandrapur', lat: 19.96, lng: 79.29, x: 0.58, y: 0.72, reports:  7, severity: 'low'    },
  { name: 'Buldhana',   lat: 20.53, lng: 76.18, x: 0.22, y: 0.58, reports:  9, severity: 'low'    },
  { name: 'Akola',      lat: 20.70, lng: 77.00, x: 0.29, y: 0.48, reports: 13, severity: 'medium' },
  { name: 'Washim',     lat: 20.10, lng: 77.15, x: 0.28, y: 0.68, reports:  5, severity: 'low'    },
]